<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\1.6\Optional\Editor\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuestEditor_Library\QuestEditor_Library.csproj" Private="false" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>
