<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath Condition=" '$(OutputPath)' == '' ">$(MSBuildThisFileDirectory)..\..\1.6\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2" />
  </ItemGroup> 

</Project>
